### ISSUE TITLE
downloading global surfaces not working

### ISSUE THREAD

**Issue by PunamA** [environmentalinformatics-marburg/chirps#5]
Hi, thank you for this wonderful package firstly (saves myself a lot of time!). 
I have been trying to download the global pentad surfaces  (if format) between a certain time period (2014 - to date). However, I keep receiving the error below:

`getCHIRPS(region = "global", format = "tifs", tres = "pentad", sres = 0.05,
          dsn = 'data',
          begin = as.Date("2014-01-01"), end = as.Date("2014-02-01"), cores = 7)`

`Error in FUN(X[[i]], ...) : subscript out of bounds `

This same function works perfectly well with Africa pentad but not with global. I checked the website and tifs exist and I can't locate where a possible bug would be in your function. Would really love some help on this if possible.

**Comment by fdetsch** [comment]
Fixed with d9c504e4519f4e890335f7248e2a25974f05c960 (likely more such fixes to come), sorry for the delay. Glad to notice there's still people using the package.
